# Generated by Django 5.0.2 on 2024-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0002_customcolumndata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcolumndata',
            name='data_type',
        ),
        migrations.AddField(
            model_name='customcolumndata',
            name='column_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customcolumndata',
            name='input_type',
            field=models.CharField(max_length=50),
        ),
    ]
